// CourseData cấp dữ liệu cho Course.jsx
// Chia nhỏ thành từng Class nhỏ để dễ quản lý

export const CourseData = [
  {
    title: 'Khóa Học Java Web Fullstack Dành Cho Người Mới Bắt Đầu',
    id: 'fullstack-nonIt-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/java-nonit.png',
    href: '/FullStack',
  },
  {
    title: 'Khóa Học Project Management Profesional Exam Prepration',
    id: 'pmp-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/pmp.jpeg',
    href: '/PMP',
  },
  {
    title: 'Khóa Học Data Analyst',
    id: 'data-analyst-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/data-analyst-2-01.png',
    href: '/DataAnalyst',
  },
  {
    title: 'Khóa Học BA',
    id: 'ba-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-14.png',
    href: '/BA',
  },
  {
    title: 'Khóa Học CCBA',
    id: 'ccba-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-13.png',
    href: '/CCBA',
  },
  {
    title: 'Khóa Học Tester',
    id: 'tester-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-10.png',
    href: '/Tester',
  },

  {
    title: 'Khóa Học Tester ISTQB',
    id: 'istqb-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-12.png',
    href: '/TesterISTQB',
  },
  {
    title: 'Khóa Học Automation Test',
    id: 'automation-test-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-9.png',
    href: '/AutomationTest',
  },
  {
    title: 'Khóa Học Lập Trình Front-End',
    id: 'front-end-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-8.png',
    href: '/FrontEnd',
  },

  {
    title: 'Khóa Học Java Web Fullstack Dành Cho Người Đã Có Nền Tảng',
    id: 'fullstack-base-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/java-it.png',
    href: '#',
  },
  // {
  //   title: 'Khóa Học Lập Trình Viên Toàn Năng',
  //   id: 'developer-img',
  //   Img: 'https://vtiacademy.edu.vn/upload/images/z4815482396910-f0d09ba653d7f48702a7175f6f23aba0.jpg',
  //   href: '#',
  // },
  {
    title: 'Khóa Học AWS Certified Solutions Architect - Associate',
    id: 'aws-saa-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-4.png',
    href: '#',
  },
  {
    title: 'Khóa Học AWS Solution Architect - Professional',
    id: 'aws-pro-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-5.png',
    href: '#',
  },
  {
    title: 'Khóa Học AWS Certified Developer - Associate',
    id: 'aws-dev-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy.png',
    href: '#',
  },
  {
    title: 'Khóa học System Admin Pro',
    id: 'system-admin-pro-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/sap1.jpeg',
    href: '#',
  },
  {
    title: 'Khóa học System Admin',
    id: 'system-admin-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/z4506213063904-073fa03d0ff66b3402dce7c81037cda5.jpg',
    href: '#',
  },
  {
    title: 'Khóa Học Game Unity',
    id: 'game-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-18.png',
    href: '#',
  },
  {
    title: 'Khóa Học Lập Trình Di Động Đa Nền Tảng Flutter',
    id: 'flutter-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/flutter-1.png',
    href: '#',
  },
  {
    title: 'Khóa Học DevOps',
    id: 'devOps-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-16.png',
    href: '#',
  },
  {
    title: 'Khóa Học Project Management',
    id: 'management-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-6.png',
    href: '#',
  },
  {
    title: 'Khóa Học IT Comtor',
    id: 'it-comtor-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/z4529351861060-da64c3f22683aa4af8599998ecc68cf0.jpg',
    href: '#',
  },
  {
    title: 'Khóa học CEH',
    id: 'ceh-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/chuong-trinh-dao-tao/ceh.png',
    href: 'https://vtiacademy.edu.vn/khoa-hoc-ceh.html',
  },
  {
    title: 'Khóa Học AI (Trí Tuệ Nhân Tạo) Toàn Diện',
    id: 'al-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/tri-tue-nhan-tao-ai-toan-dien.jpeg',
    href: '#',
  },
  {
    title: 'Khóa Học Python',
    id: 'python-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-3.png',
    href: '#',
  },
  {
    title: 'Khóa Học Kỹ Sư Cầu Nối Nhật Bản',
    id: 'bridge-japan-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1.png',
    href: '#',
  },
  {
    title: 'Khóa Học Kỹ Sư Cầu Nối Hàn Quốc',
    id: 'bridge-korea-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-19.png',
    href: '#',
  },
  {
    title: 'Khóa Học LPIC 1',
    id: 'LPIC-1-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/lpic.jpeg',
    href: '#',
  },
  {
    title: 'Khóa Học Senior Scrum Master',
    id: 'scrum-master-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/scrum.jpeg',
    href: '#',
  },
  {
    title: 'Khóa Học CCNA',
    id: 'CCNA-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/ccna.jpeg',
    href: '#',
  },
  {
    title: 'Khóa Học Coaching On Job',
    id: 'coaching-on-job-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/coaching-on-job-2.png',
    href: '#',
  },
  {
    title: 'Khóa Học UX',
    id: 'UX-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/z4631403166680-1b6fdd6a044aeb37f226e7cff21a4481.jpg',
    href: '#',
  },
  {
    title: 'Khóa Học UI',
    id: 'UI-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/z4631403179104-c4d143ef3a9ac16b269ece70f7c04cc1.jpg',
    href: '#',
  },
  {
    title: 'Khóa Học Node JS',
    id: 'node-js-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-17.png',
    href: '#',
  },
  {
    title: 'Khóa Học Lập Trình Mobile (Android)',
    id: 'mobile-android-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/z4352594831618-346c8610572d61a5c335261d61f310ff.jpg',
    href: '#',
  },
  {
    title: 'Khóa Học Blockchain',
    id: 'blockchain-img',
    Img: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-2.png',
    href: '#',
  },
];
