export const CoachData = [
  {
    name: 'Trần Xuân Khôi',
    img: 'https://vtiacademy.edu.vn/upload/images/anh-khoi(1).png',
    row1: 'Chủ tịch Hội đồng quản trị kiêm Tổng giám đốc VTI Group',
    row2: 'Chuyên gia CNTT hàng đầu Việt Nam ',
    row3: 'Kinh nghiệm: 23+ năm kinh nghiệm trong ngành CNTT Các đơn vị từng công tác: FPT Software',
  },
  {
    name: 'Nguyễn Quyết',
    img: 'https://vtiacademy.edu.vn/upload/images/a-quyet(1).png',
    row1: 'CEO VTI Academy Chuyên gia CNTT hàng đầu',
    row2: ' Kinh nghiệm: 13+ năm kinh nghiệm trong ngành CNTT',
    row3: 'Các đơn vị từng công tác: FPT University, FPT Software, CMC Coporation, Trainocate',
  },
  {
    name: 'Đào Duy Hoàng',
    img: 'https://vtiacademy.edu.vn/upload/images/dao-duy-hoang.png',
    row1: 'Kinh nghiệm: 6+ năm kinh nghiệm trong ngành CNTT ',
    row2: 'Vị trí hiện tại: Fronter End Leader Participate in project of Samsung Sds Viet Nam',
    row3: 'Các đơn vị từng công tác: PRODUCTION MANAGEMENT PROJECT FOR NHON HOA COMPANY, AVG TV ONLINE PAYMENT WEB PROJECT, BUILDING A CUSTOMER RELATIONSHIP MANAGEMENT SYSTEM GOEDU COMPANY',
    row4: 'Ngoại ngữ: Tiếng Anh',
  },
  {
    name: 'Trương Huy Hoàng Anh',
    img: 'https://vtiacademy.edu.vn/upload/images/truong-huy-hoang-anh.png',
    row1: ' Kinh nghiệm: 10+ năm kinh nghiệm trong ngành CNTT',
    row2: ' Vị trí hiện tại: BUSINESS ANALYST - ATI - INNOVATIONLAB MB',
    row3: 'Các đơn vị từng công tác: DTT GROUP, VNRESOURCE SOFTWARE SOLUTIONS, MEKONG RESOURCES - AGILSUN',
    row4: 'Ngoại ngữ: Tiếng Anh',
  },
  {
    name: 'Trần Nguyễn Phương Nam',
    img: 'https://vtiacademy.edu.vn/upload/images/tran-nguyen-phuong-nam.png',
    row1: 'Kinh nghiệm: 4+ năm kinh nghiệm trong ngành CNTT',
    row2: 'Vị trí hiện tại: Senior Devops Engineer - CMC Global',
    row3: ' Các đơn vị từng công tác: Flinters VietNam, Goaw VietNam',
    row4: ' Ngoại ngữ: Tiếng Anh',
    row5: ' Chứng chỉ: Thủ khoa tốt nghiệp ngành Mạng máy tính và Truyền thông dữ liệu, Trường Đại học Công nghệ – ĐHQGHN AWS Certified Solutions Architect - Associate AWS Certified Development - Associate',
  },
  {
    name: 'Nguyễn Văn Sơn',
    img: 'https://vtiacademy.edu.vn/upload/images/son-o-to-2.png',
    row1: 'Kinh nghiệm: 14+ năm kinh nghiệm trong ngành CNTT',
    row2: 'Vị trí hiện tại: Làm freelancer',
    row3: 'Các đơn vị từng công tác: Trưởng phòng kỹ thuật- Công ty Cổ phần Dịch vụ Viễn thông SunTel Việt Nam, NextG Solutions, Fsoft',
    row4: ' Ngoại ngữ: Tiếng Anh',
  },
  {
    name: 'Nguyễn Sơn Hải',
    img: 'https://vtiacademy.edu.vn/upload/images/son-hai(1).png',
    row1: 'Kinh nghiệm: 7+ năm kinh nghiệm trong ngành CNTT',
    row2: 'Vị trí hiện tại: Niteco - Infrastructure/Devops Specialist',
    row3: 'Các đơn vị từng công tác: Samsung SDSV, Hanoi french Hospital',
    row4: ' Ngoại ngữ: Tiếng Anh',
  },
  {
    name: 'Lưu Minh Tiến',
    img: 'https://vtiacademy.edu.vn/upload/images/luu-quang-tien.png',
    row1: 'Kinh nghiệm: 13+ năm kinh nghiệm trong ngành CNTT',
    row2: ' Vị trí hiện tại: Project Management Officer- Luvina Software',
    row3: 'Các đơn vị từng công tác: FPT Software, Viettel Group, VMO Group',
    row4: 'Ngoại ngữ: Tiếng Anh, Tiếng Pháp, Tiếng Nhật',
    row5: ' Chứng chỉ: Certified Software Quality Analyst(CSQA), Information Security Management, Scrum Master Certified (SMC), Official CMMI Introduction Training',
  },
  {
    name: 'Đỗ Thị Ngà',
    img: 'https://vtiacademy.edu.vn/upload/images/nga-ba.png',
    row1: ' Kinh nghiệm: 14+ năm kinh nghiệm trong ngành CNTT',
    row2: ' Vị trí hiện tại: Business Analyst - VIETTEL SOFTWARE SERVICES',
    row3: 'Các đơn vị từng công tác: FPT SOFTWARE, CÔNG TY CP CÔNG NGHỆ TIN HỌC EFY VIỆT NAM, CÔNG TY CP PHẦN MỀM PHƯƠNG ĐÔNG',
    row4: ' Ngoại ngữ: Tiếng Anh',
    row5: 'Chứng chỉ: Outsystem Associate, Professional Scrum Master, Professional Scrum Product Owner',
  },
  {
    name: 'Nguyễn Vinh Hiển',
    img: 'https://vtiacademy.edu.vn/upload/images/nguyen-vinh-hien.png',
    row1: ' Kinh nghiệm: 10+ năm kinh nghiệm trong ngành CNTT',
    row2: ' Vị trí hiện tại: STC Group - PM',
    row3: 'Các đơn vị từng công tác: HiPT, FSC.',
    row4: 'Ngoại ngữ: Tiếng Anh',
  },
  {
    name: 'Nguyễn Quốc Cường',
    img: 'https://vtiacademy.edu.vn/upload/images/nguyen-quoc-cuong.png',
    row1: ' Kinh nghiệm: 3+ năm kinh nghiệm trong ngành CNTT',
    row2: 'Vị trí hiện tại: Samsung Vietnam Mobile RnD Center- Engineer',
    row3: ' Các đơn vị từng công tác: Samsung',
    row4: 'Ngoại ngữ: Tiếng Anh',
  },
  {
    name: 'Đỗ Văn Quang',
    img: 'https://vtiacademy.edu.vn/upload/images/do-quang(1).png',
    row1: ' Kinh nghiệm: 3+ năm kinh nghiệm trong ngành CNTT ',
    row2: 'Vị trí hiện tại: Samsung Vietnam Mobile R&D Center- Android Application',
    row3: ' Các đơn vị từng công tác: Samsung  ',
    row4: ' Ngoại ngữ: Tiếng Anh',
  },
  {
    name: 'Trần Ngọc Sơn',
    img: 'https://vtiacademy.edu.vn/upload/images/son-tran-son-tran.png',
    row1: 'Kinh nghiệm: 8+ năm kinh nghiệm trong ngành CNTT ',
    row2: ' Vị trí hiện tại: CyberLogitec Viet Nam - Team Lead, PM  ',
    row3: ' Các đơn vị từng công tác: TMA Solutions, Axon Active VietNam,Hansen Technologies, CyberLogitec Viet Nam.',
    row4: ' Ngoại ngữ: Tiếng Anh',
    row5: 'Chứng chỉ: Professional Scrum for Developer, Fit for Scrum',
  },
  {
    name: 'Nguyễn Tiến Hải',
    img: 'https://vtiacademy.edu.vn/upload/images/tien-hai.png',
    row1: 'Kinh nghiệm: 9+ năm kinh nghiệm trong ngành CNTT   ',
    row2: 'Vị trí hiện tại: AWS Solutions Architect - Megazone Cloud',
    row3: 'Các đơn vị từng công tác: VTI Cloud, KDDI Vietnam, Kumoh National Institute of Technology',
    row4: ' Ngoại ngữ: Tiếng Anh',
    row5: ' Chứng chỉ: AWS Certified Solutions Architect - Professional (AWS-SAP), AWS Certified Solutions Architect - Associate (AWS-SAA), Cisco Certified Network Associate Routing and Switching (CCNA R&S).',
  },
  {
    name: 'Nguyễn Văn Quyền',
    img: 'https://vtiacademy.edu.vn/upload/images/nguyen-van-quyen.png',
    row1: 'Kinh nghiệm: 5+ năm kinh nghiệm trong ngành CNTT',
    row2: 'Vị trí hiện tại: Senior DevOps - National Australia Bank Innovation Central Vietnam (NICV)',
    row3: ' Các đơn vị từng công tác: FSOFT',
    row4: 'Ngoại ngữ: Tiếng Anh',
    row5: 'Chứng chỉ: Microsoft Certified: Azure Solutions Architect Expert, Microsoft Certified: Azure Network Associate, Azure Security Engineer Associate, AWS Solution Architect',
  },
  {
    name: 'Lê Khắc Hậu Linh',
    img: 'https://vtiacademy.edu.vn/upload/images/hau-linh(1).png',
    row1: 'Kinh nghiệm: 4+ năm kinh nghiệm trong ngành CNTT',
    row2: 'Vị trí hiện tại: Front End Leader - iLotusLand',
    row3: 'Ngoại ngữ: Tiếng Anh',
    row4: 'Chứng chỉ: VNUHCM-University of Information Technology (VN) - Software Engineering',
  },
];
