export const Data = {
  imgBanners:
    'https://vtiacademy.edu.vn/upload/images/z4713894473283-471e4cfa8d475a3f09f9d97e4d22aa18.jpg',
  imgIntroduction:
    'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-16-100.jpg',
  introduction:
    'Với khung chương trình bám sát yêu cầu dự án thực tế, khi tham gia khóa học, các bạn sẽ được trang bị đầy đủ kiến thức từ cơ bản tới nâng cao để trở thành một Front-end Developer.',
  iconLogo: 'https://vtiacademy.edu.vn/template/frontend/images/logo-ngang.png',

  participants1:
    'Sinh viên ngành CNTT muốn học bài bản và nâng cao kỹ năng về Lập trình Front-End với React JS',
  participants2:
    'Lập trình viên đang làm việc tại các doanh nghiệp muốn bổ sung kiến thức nền tảng, kỹ năng thực hành về Front-end chuyên sâu với React JS',
  participants3: 'Người muốn chuyển ngành sang lập trình',
  wheredowork1:
    'Apply vào tất cả công ty tuyển dụng Front-end Dev hoặc Fresher',
  wheredowork2: 'Các công ty outsourcing - gia công phần mềm',
  wheredowork3: 'Công ty, tập đoàn trong nước và nước ngoài...',
  wheredowork4: 'Các công ty startup - khởi nghiệp',
  wheredowork5: 'Nhận các job freelance về xây dựng Front-end',

  // BOX-4
  imgBox4: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-16-100.jpg',
  box4_row1:
    'Làm chủ HTML, CSS, JavaScript, thư viện Bootstrap, Jquery trong xây dựng giao diện web',
  box4_row2: 'Làm chủ thư viện ReactJS, các khái niệm từ cơ bản đến nâng cao',
  box4_row3:
    'Tạo ra sản phẩm thực tế ngay trong khóa học, xây dựng projet phù hợp với yêu cầu doanh nghiệp',
  box4_row4:
    'Hiểu về quy trình phát triển sản phẩm phần mềm khi làm việc trong doanh nghiệp',
  box4_row5:
    'Sẵn sàng tham gia dự án ở vai trò lập trình viên Front-end với ReactJS',

  // BOX-5
  // Module-1
  module1_title: 'Module 1: Các khái niệm cơ bản về Business Analysis',
  day1: 'Học phần 1: Basic Web',
  day1: 'Day 1',
  module1_row1: 'Giới thiệu về khóa học',
  module1_row2: 'Bài giảng HTML',
  module1_row3: 'Thực hành',
  day2: 'Day 2',
  module1_row4: 'Review Assignment & Lý thuyết Day 1',
  module1_row5: 'Bài giảng CSS Basic',
  module1_row6: 'Thực hành',
  day3: 'Day 3',
  module1_row7: 'Review Assignment & Lý thuyết Day 2',
  module1_row8: 'Bài giảng CSS Extra',
  module1_row9: 'Thực hành',
  day4: 'Day 4',
  module1_row10: 'Bài giảng CSS Layout',
  module1_row11: 'Thực hành',
  day5: 'Day 5',
  module1_row12: 'Bài giảng Boostrap',
  module1_row13: 'Bài giảng SASS',
  module1_row14: 'Thực hành',
  day6: 'Day 6',
  module1_row15: 'Bài giảng HTML3 CSS3',
  module1_row16: 'Bài giảng Responsive khi làm giao diện website',
  module1_row17: 'Thực hành',
  module1_row18: 'Review, tổng kết kiến thức Package 1',
  module1_img: 'https://vtiacademy.edu.vn/upload/images/10.png',

  // Module-2
  module2_img: 'https://vtiacademy.edu.vn/upload/images/11.png',
  module2_title: 'Học phần 2: ECMAScript 6 (ES6) - JavaScript Advanced',
  day1: 'Day 1',
  module2_row1: 'Giới thiệu',
  module2_row2: 'Bài giảng: JavaScript',
  module2_row3: 'Thực hành',
  day2: 'Day 2',
  module2_row4: 'Review Assignment & Lý thuyết Day 1',
  module2_row5: 'Bài giảng: Thư viện Jquery',
  module2_row6: 'Thực hành',
  day3: 'Day 3',
  module2_row7: 'Bài giảng: LocalStorage_SessionStorage_Cookie',
  module2_row8: 'Thực hành',
  day4: 'Day 4',
  module2_row9: 'Bài giảng: Sử dụng GIT trong quản lý Source Code',
  module2_row10: 'Thực hành',
  day5: 'Day 5',
  module2_row11: 'Review Project học viên',
  module2_row12: 'Thực hành',
  day6: 'Day 6',
  module2_row13: 'Bài giảng: Sử dụng AJAX load dữ liệu bất đồng bộ',
  module2_row14: 'Thực hành',
  day7: 'Day 7',
  module2_row15: 'Review Project học viên',
  module2_row16: 'Thực hành',
  day8: 'Day 8',
  module2_row17: 'Exam',

  // Module-3
  module3_img: 'https://vtiacademy.edu.vn/upload/images/11.png',
  module3_title: 'Học phần 3: React Basic',
  module3_row1: 'Giới thiệu',
  module3_row2: 'Bài giảng: TypeScript',
  module3_row3: 'Bài giảng: TypeScript',
  module3_row4: 'Thực hành',
  module3_row5: 'Bài giảng: JavaScript Advanced',
  module3_row6: 'Thực hành',
  module3_row7: 'Bài giảng: JavaScript Advanced',
  module3_row8: 'Thực hành',
  module3_row9:
    'Bài giảng: ReactJS, First Program, JSX, Class Component, Function Component, Container Component, UI Component, Style trong React',
  module3_row10: 'Thực hành',
  module3_row11: 'Bài giảng: ReactJS, Fragment, State, Props, Form, Event',
  module3_row12: 'Thực hành',
  module3_row13: 'Bài giảng: Render Element trong React',
  module3_row14: 'Thực hành',
  module3_row15: 'Bài giảng: ReactJS, Share Data Component',
  module3_row16: 'Thực hành',
  module3_row17: 'Bài giảng: ReactJS, Lifecycle, Hook(useState, useEffect)',
  module3_row18: 'Thực hành',
  module3_row19: 'Thực hành',
  module3_row20: 'Thực hành',
  module3_row21: 'Review Project, tổng kết Package',

  // Module-4
  module4_img: 'https://vtiacademy.edu.vn/upload/images/11.png',
  module4_title: 'Học phần 4: React Advanced',
  day1: 'Day 1',
  module4_row1: 'Giới thiệu',
  module4_row2: 'Bài giảng: Thao tác Call API trong ứng dụng React',
  module4_row3: 'Bài giảng: Kỹ thuật HOC trong React',
  module4_row4: 'Thực hành',
  day2: 'Day 2',
  module4_row5: 'Review bài tập Day 1',
  module4_row6: 'Thực hành',
  day3: 'Day 3',
  module4_row7: 'Review bài tập Day 2',
  module4_row8: 'Bài giảng: Redux Core',
  day4: 'Day 4',
  module4_row9: 'Bài giảng: React Redux',
  module4_row10: 'Thực hành',
  day5: 'Day 5',
  module4_row11: 'Bài giảng: React Thunk, tích hợp Redux Dev Tools',
  module4_row12: 'Thực hành',
  day6: 'Day 6',
  module4_row13: 'Thực hành',
  day7: 'Day 7',
  module4_row14: 'Bài giảng: Redux Tool Kit',
  module4_row15: 'Thực hành',
  day8: 'Day 8',
  module4_row16: 'Bài giảng: Thư viện React Router',
  module4_row17: 'Thực hành',
  day9: 'Day 9',
  module4_row18: 'Bài giảng: Thư viện Fomik, Yup',
  module4_row19: 'Thực hành',
  day10: 'Day 10',
  module4_row20: 'Bài giảng: Hook Advanced',
  module4_row21: 'Thực hành',
  day11: 'Day 11',
  module4_row22: 'Review bài tập Day 10',
  module4_row23: 'Bài giảng: Deploy sản phẩm',
  day12: 'Day 12',
  module4_row24: 'Bài giảng: Deploy sản phẩm',
  module4_row25: 'Review Project, tổng kết Package',

  // Module-5
  module5_img: 'https://vtiacademy.edu.vn/upload/images/11.png',
  module5_title: 'Học phần 5: Ready with React Dev',
  day1: 'Day 1',
  module5_row1: 'Giới thiệu',
  module5_row2: 'Bài giảng: Agile Scrum',
  day2: 'Day 2',
  module5_row3: 'Bài giảng: Agile Scrum',
  module5_row4: 'Review CV học viên',
  day3: 'Day 3',
  module5_row5: 'Review kiến thức trong khóa học',
  module5_row6: 'Review Project học viên',
  day4: 'Day 4',
  module5_row7: 'Exam',
};
