export const Data = {
  imgBanners:
    'https://vtiacademy.edu.vn/upload/images/z4713894473283-471e4cfa8d475a3f09f9d97e4d22aa18.jpg',
  imgIntroduction:
    'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-3-100.jpg',
  introduction:
    'Chương trình đào tạo Tester chú trọng vào thực tế – chỉ đào tạo những kiến thức, kỹ năng doanh nghiệp cần, đã trở thành bệ phóng cho hàng ngàn học viên đã tốt nghiệp và có việc làm ổn định ở các công ty, tập đoàn lớn trong và ngoài nước. Đặc biệt khóa học được thiết kế phù hợp cho các bạn sinh viên, người đang đi học, đi làm và cả các bạn có nhu cầu chuyển ngành. ',
  iconLogo: 'https://vtiacademy.edu.vn/template/frontend/images/logo-ngang.png',
  participants1: 'Người muốn tìm công việc ổn định, lương cao',
  participants2:
    'Người muốn làm việc trong ngành CNTT nhưng không phải code nhiều',
  participants3: 'Người có định hướng trở thành Tester',

  wheredowork1: 'Apply vào tất cả công ty tuyển dụng Tester',
  wheredowork2: 'Các công ty outsourcing - gia công phần mềm',
  wheredowork3: 'Công ty, tập đoàn trong nước và nước ngoài...',
  wheredowork4: 'Các công ty startup - khởi nghiệp',
  wheredowork5: 'Nhận các job freelance về Tester',

  // BOX-4
  imgBox4: 'https://vtiacademy.edu.vn/upload/images/artboard-1-copy-3-100.jpg',
  box4_row1: 'Nắm chắc các kiến thức về kiểm thử phần mềm.',
  box4_row2:
    'Thực hiện được kiểm thử các phần mềm một cách chuyên nghiệp trên đa dạng các loại ứng dụng với các nền tảng khác nhau',
  box4_row3:
    'Sử dụng thành thạo hầu hết các kỹ thuật kiểm thử, thiết kế kiểm thử và viết test case',
  box4_row4: 'Sẵn sàng tham gia dự án ở vai trò Tester',
  // BOX-5
  // Module-1
  module1_img: 'https://vtiacademy.edu.vn/upload/images/10.png',
  module1_title: 'Học phần 1: Basic SQL with MySQL',
  day1: 'Day 1: RDBMS & MySQL Part 1: Giới thiệu về RDBMS',
  module1_row1: 'Giới thiệu về khóa học các Databases, SQL và MySQL',
  module1_row2: 'Cài đặt MySQL và tìm hiểu giao diện MySQL',
  module1_row3: 'Thực hành kiến thức đã học ở phần trên',
  module1_row4:
    'Các thuật ngữ database cơ bản (PrimaryKey, ForeignKey, Unique, Default, Not null)',
  module1_row5: 'Thực hành kiến thức đã học ở phần trên',
  module1_row6: 'Giao bài tập & Gợi ý cách thực hiện (Assignment 01)',
  day2: 'Day 2: RDBMS & MySQL Part 2: Định nghĩa dữ liệu (DDL) ',
  module1_row7: 'Review bài tập Day 1',
  module1_row8: 'Nhập môn SQL (tạo database, tạo bảng, datatype)',
  module1_row9:
    'Các ràng buộc dữ liệu (PrimaryKey, ForeignKey, Unique, value null, relationship table: 1 nhiều, nhiều nhiều)',
  module1_row10: 'Thực hành kiến thức đã học ở phần trên',
  module1_row11: 'SQL Best Practice',
  module1_row12: 'Thực hành kiến thức đã học ở phần trên',
  module1_row13: 'Giao bài tập & Gợi ý cách thực hiện (Assignment 02)',
  day3: 'Day 3: RDBMS & MySQL Part 3: Thao tác dữ liệu (DML)   ',
  module1_row14: 'Review bài tập Day 2',
  module1_row15: 'Import database',
  module1_row14:
    'Lệnh SELECT và các toán tử AND, OR, IN và Not IN, Like và Not Like, BETWEEN AND, IS NOT NULL và IS NULL, Order by, Group By, HAVING, Alias, LIMIT',
  module1_row17: 'Thực hành kiến thức đã học ở phần trên',
  module1_row18: 'INSERT và INSERT INTO; UPDATE; DELETE, TRUNCATE, DROP',
  module1_row19: 'Thực hành kiến thức đã học ở phần trên',
  module1_row20: 'Giao bài tập & Gợi ý cách thực hiện (Assignment 03)',
  day4: 'Day 4: RDBMS & MySQL Part 4: Ôn tập & Exam',
  module1_row21: 'Review bài tập Day 3',
  module1_row22: 'Các hàm thưởng sử dụng',
  module1_row23:
    'Các loại JOINs (Inner Join, Left Join, Right Join, Join và Where, Cross Join, Union và Union All',
  module1_row24: 'Thực hành kiến thức đã học ở phần trên',
  module1_row25: 'Giải một số câu hỏi khó trong bài thi tự luận',

  // Module-2
  module2_img: 'https://vtiacademy.edu.vn/upload/images/11.png',
  module2_title: 'Học phần 2: Software Testing Foundation',
  day5: 'Day 5: Software Testing',
  module2_row1:
    'Giới thiệu tổng quan về dự án phần mềm (overview dự án, type dự án, role & responsibility)',
  module2_row2: 'Mô hình phát triển phầm mềm',
  module2_row3: 'Testing là gì?',
  module2_row4: 'Tại sao cần testing?',
  module2_row5: 'Summary nội dung buổi học',
  day6: 'Day 6: Seven Testing Principles & Software Testing Process',
  module2_row6: 'Review bài tập Day 5',
  module2_row7: '7 nguyên lý trong testing',
  module2_row8: 'Test Process',
  module2_row9: 'Test Activities',
  module2_row10: 'Summary nội dung buổi học',
  day7: 'Day 7: Testing Level',
  module2_row11: 'Review bài tập Day 6',
  module2_row12: 'Unit Testing - Integration Testing',
  module2_row13: 'System Testing - User Acception Testing',
  module2_row14: 'Thực hành kiến thức đã học ở phần trên',
  module2_row15: 'Summary nội dung buổi học',
  day8: 'Day 8: Test Type',
  module2_row16: 'Review bài tập Day 7',
  module2_row17:
    'Understand test types: Functional Testing and  Non_Functional Testing, Re-testing & Regression testing, Alpha Testing and Beta Testing, Structure Testing',
  module2_row18: 'Thực hành kiến thức đã học ở trên',
  module2_row19: 'Summary nội dung buổi học',
  day9: 'Day 9: Static Testing Basic',
  module2_row20: 'Review bài tập Day 8',
  module2_row21: 'Maintenance Testing',
  module2_row22: 'Static Testing Basics Part 1',
  module2_row23: 'Static Testing Basics Part 2',
  module2_row24: 'Summary nội dung buổi học',
  day10: 'Day 10: Test Techniques Black-box: EP, VBA    ',
  module2_row25: 'Review bài tập Day 9',
  module2_row26: 'Categories of Test Techniques',
  module2_row27: 'Black-box Test Techniques: EP, BVA',
  module2_row28: 'Thực hành kiến thức đã học ở trên - Quiz - Assignment',
  day11:
    'Day 11: Test Techniques Black-box: State Transition Testing White-box',
  module2_row29: 'Review bài tập Day 10',
  module2_row30: 'Black-box Test Techniques: Decision Table Testing',
  module2_row31: 'Black-box Test Techniques: State Transition Testing ',
  module2_row32: 'Thực hành kiến thức đã học ở trên - Quiz - Assignment',
  day12: 'Day 12: Test Techniques Experience-based Test Plan',
  module2_row33: 'Review bài tập Day 11',
  module2_row34: 'White-box Test Techniques',
  module2_row35: 'Experience-based Test Techniques ',
  module2_row36: 'Thực hành kiến thức đã học ở trên - Quiz - Assignment',
  day13: 'Day 13: Test Plan & Test Design',
  module2_row37: 'Review bài tập Day 12',
  module2_row38: 'Test Plan - How to study requirement - How to estimate test',
  module2_row39: 'Analyze and Design Tests',
  module2_row40: 'Thực hành kiến thức đã học ở trên - Quiz - Assignment',
  day14: 'Day 14: Test analysis practice',
  module2_row41: 'Review bài tập Day 13',
  module2_row42: 'Nghiên cứu requirement',
  module2_row43: 'Phân tích requirement',
  module2_row44: 'Question & Answer',
  module2_row45: 'Create Test Condition',
  day15: 'Day 15: Test Case',
  module2_row46: 'Review bài tập Day 14',
  module2_row47: 'Test Case : Test Web',
  module2_row48: 'Thực hành kiến thức đã học ở trên',
  module2_row49: 'Test Case: Test Mobile',
  module2_row50: 'Thực hành kiến thức đã học ở trên - Quiz - Assignment',
  day16: 'Day 16: Test Case (cont.)',
  module2_row51: 'Review bài tập Day 15',
  module2_row52: 'Thực hành nghiên cứu SRS',
  module2_row53: 'Thực hành viết test case',
  day17: 'Day 17: Thực hành phân tích tĩnh  ',
  module2_row54: 'Thực hành review testcase',
  module2_row55: 'Trình bày quan điểm review',
  day18: 'Day 18: Execution Test & Log Defect',
  module2_row56: 'Review bài tập Day 15',
  module2_row57: 'How to execute test effecially',
  module2_row58: 'Thực hành kiến thức đã học ở trên',
  module2_row59: 'Bug and how to report bug',
  module2_row60: 'Thực hành kiến thức đã học ở trên - Quiz - Assignment',
  day19: 'Day 19: Execution Test & Log Defect(cont.)',
  module2_row61: 'Thực hành execute testing',
  module2_row62: 'Bug and how to report bug',
  day20: 'Day 20: Test Report & Test Tools  ',
  module2_row63: 'Review bài tập Day 16',
  module2_row64: 'Test Report',
  module2_row65: 'How to use some Test Tools',
  module2_row66: 'Thực hành kiến thức đã học ở trên - Quiz - Assignment',

  // Module-3
  module3_img: 'https://vtiacademy.edu.vn/upload/images/6.png',
  module3_title: 'Học phần 3: Test Mock Project',
  day21: 'Day 21: Bài tập lớn',
  module3_row1: 'Nghiên cứu requirement',
  module3_row2: 'Phân tích requirement',
  module3_row3: 'Thực hành tạo quan điểm testing',
  day22: 'Day 22: Bài tập lớn(cont.)   ',
  module3_row4: 'Review quan điểm testing',
  module3_row5: 'Thực hành tạo test case',
  day23: 'Day 23: Bài tập lớn(cont.)',
  module3_row6: 'Review tạo test case',
  module3_row7: 'Tổng kết đánh giá MP',

  // Module-4
  module4_img: 'https://vtiacademy.edu.vn/upload/images/4(1).png',
  module4_title: 'Package 4: API Testing',
  day24: 'Day 24: Tổng quan API 01',
  module4_row1: 'Tổng quan về kiến trúc services và mô hình triển khai thực tế',
  module4_row2: 'Tổng quan về API và các đặc điểm HTTP (Method/Code)',
  module4_row3: 'Tại sao cần kiểm thử API sớm & hạng mục kiểm thử API',
  day25: 'Day 25: Tổng quan API 02',
  module4_row4: 'Authen & Authorization trong kiểm thử API',
  module4_row5: 'Tổng quan về Token trong API (Access & Refresh)',
  module4_row6: 'Phương thức & Cách thức nghiên cứu, tìm hiểu tài liệu API',
  day26: 'Day 26: Xây dựng kịch bản kiểm thử API',
  module4_row7: 'Tư duy kiểm thử API',
  module4_row8: 'Tiêu chuẩn test case cho API',
  module4_row9: 'Thực hành phân tích API & Xây dựng test design/test case',
  day27: 'Day 27: Xây dựng test script trên Postman',
  module4_row10: 'Thực hành xây dựng kịch bản kiểm thử API',
  module4_row11: 'Tổng quan về Postman',
  module4_row12: 'Quy chuẩn log bug trong API',
  module4_row13: 'Thực hành kiểm thử API',
  day28: 'Day 28: Thực hành kiểm thử API',
  module4_row14: 'Thực hành viết test case',
  module4_row15: 'Thực hành kiểm thử API',

  // Module-5
  module5_img: 'https://vtiacademy.edu.vn/upload/images/5(1).png',
  module5_title: 'Exam',
  day29: 'Day 29: Summary',
  module5_row1: 'Question & Answer trong phỏng vấn Tester',
  module5_row2: 'Hướng dẫn làm CV ',
  day30: 'Day 30: Exam',
  module5_row3: 'Bài thi cuối khóa',
};
